### ISSUE TITLE
Bug: custom image fields don't appear in PHP 7

### ISSUE THREAD

**Issue by jlahijani** [justb3a/processwire-imageextra#20]
This plugin works fine in PHP 5.5 (5.5.12 to be exact), but in PHP 7, everything works except the custom image fields do not appear.

I'm using PW 3.0.33 if that matters.

Weird issue but I was able to confirm it.

**Comment by justb3a** [comment]
hi,
I use this module in several projects (ProcessWire 3.x) using PHP56 (also developed the module using PHP56) and everything works as expected. Locally I just switched to PHP7 to test the module and everything is working too. Furthermore I've no idea why the module should stop working using a newer php version, using an older php version may be problematic. Does the environments differ apart from the php version? Do you tested it using the same installation und just changed the php version? Did you check the log files?

**Comment by jlahijani** [comment]
Yes, I tested it on the same server using a different PHP version (used Cpanel to easily switch versions).  The log files don't indicate any errors or exceptions.

Actually it works on 5.6 too.  My mistake.  It's just 7 that's not working.  I will do more tests.

**Comment by Toutouwai** [comment]
I'm experiencing the same problem in PHP7 (local dev site running under XAMPP).

The same field, in PHP 5.5 vs PHP7:
![php5](https://cloud.githubusercontent.com/assets/1538852/19025488/f8a3b206-8975-11e6-8f8c-460de01f5da1.png)
![php7](https://cloud.githubusercontent.com/assets/1538852/19025487/f8a1707c-8975-11e6-8b14-2c9dbe56cb5c.png)

**Comment by Toutouwai** [comment]
I think the cause may in this line: https://github.com/justb3a/processwire-imageextra/blob/master/ImageExtra.module#L88

I don't know why this would have changed in PHP7, but it seems you cannot access $this->input inside the empty() function.

Possible alternatives for line 88:
`if (wire('page')->template->name === 'admin' && !empty($this->wire('input')->get->id) || wire('page')->template->name != 'admin') {`
...or remove the !empty() because it isn't really necessary...
`if (wire('page')->template->name === 'admin' && $this->input->get->id || wire('page')->template->name != 'admin') {`

**Comment by justb3a** [comment]
I removed the `!empty` check and fixed another PHP7 error. Could you please check whether it's working now?

**Comment by Toutouwai** [comment]
Thanks, working for me. Could you please bump up the module version number so the update gets prompted in the PW Upgrades module?

**Comment by justb3a** [comment]
👍  I bump the module version later this day. First I wanted to know if everything works as expected. Furthermore I want to include a feature request as well: [Allow labels for custom fields](https://processwire.com/talk/topic/9056-module-image-extra/?page=3#comment-129598)
